version: 2.1

commands:
    pytest:
        steps:
            - checkout
            - run: pip install . --user
            - run: pip install pytest --user
            - run: python -m pytest

jobs:
    build:
        docker:
            - image: 'circleci/python:3.6'
        steps:
            - pytest
            

workflows:
    version: 2
    builds_and_test:
        jobs:
            - build