version: 2
jobs:
    build:
        docker:
            - image: 'circleci/python:3.6'
        steps:
            - checkout
            - run: pip install . --user
            - run: pip install pytest --user
            - run: python -m pytest

workflows:
    version: 2
    builds_and_test:
        jobs:
            - build