version: 2.1

commands:
    pytest:
        steps:
            - checkout
            - run: pip install . --user
            - run: pip install pytest --user
            - run: python -m pytest

jobs:
    build:
        docker:
            - image: 'circleci/python:3.6'
        steps:
            - pytest
    Python34:
        docker:
            - image: 'circleci/python:3.4'
        steps:
            - pytest
    Python35:
        docker:
            - image: 'circleci/python:3.5'
        steps:
            - pytest
    Python37:
        docker:
            - image: 'circleci/python:3.7'
        steps:
            - pytest

orbs:
    masonite: masonite/trigger@dev:latest            

workflows:
    version: 2
    builds_and_test:
        jobs:
            - build
            - Python34
            - Python35
            - Python37
            - masonite/deploy:
                username: josephmancuso
                filters:
                    tags:
                        only: /^v.*/
                branches:
                    ignore: /.*/
                requires:
                    - build