version: 2
jobs:
    build:
        docker:
            - image: 'circleci/python:3.6'
        steps:
            - checkout
            - python -m pytest

workflows:
    version: 2
    builds_and_test:
        jobs:
            - build